kind: Service
apiVersion: v1
metadata:
  name: locust-master-partner
spec:
  type: LoadBalancer
  selector:
    app: locust-master-partner
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
