apiVersion: v1
kind: ConfigMap
metadata:
  name: galop-config
data:
  LOCUST_MODE_MASTER: master
  LOCUST_MODE_WORKER: worker
  ASP_TASK_FILE: asp-tasks.py
  I_TASK_FILE: i-tasks.py
  MARCHANT_TASK_FILE: marchant-tasks.py
  PARTNER_TASK_FILE: partner-tasks.py
  ADMIN_USER_NAME: nextlevel
  ADMIN_PASSWORD: nhRiBHQeM97G
  ASP_HOST: http://asp.sl-galop-main.xyz
  I_HOST: http://i.sl-galop-main.xyz
  MARCHANT_HOST: http://marchant.sl-galop-main.xyz
  PARTNER_HOST: http://partner.sl-galop-main.xyz
