apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: master
          image: gcr.io/nextlevel-serverless-galop-dev/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: TASK_FILE
              value: tasks.py
            - name: LOGIN_USER_NAME
              value: nextlevel
            - name: LOGIN_PASSWORD
              value: nhRiBHQeM97G
            - name: LOCUST_TARGET_HOST
              value: http://asp.sl-galop-main.xyz
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
